#!/bin/sh

set -e
set -x

. ./common

setup() {
    apk --no-cache add \
        alpine-sdk \
        sudo \
        bash \
        python3-dev \
        py3-pip \
        patchelf \
        linux-headers \
        curl
    chown -R runner /usr/local
}

library() {
    build_library
}

wheel() {
    install_build_wheel
    build_wheel
}

$1
