#!/bin/sh

BASE="$PWD"
LIBRARY_DIR="$BASE/tkrzw-$TKRZW_VERSION"
MODULE_DIR="$BASE/tkrzw-python-$TKRZW_PYTHON_VERSION"

export PYENV_ROOT="$BASE/pyenv"
export PATH="$PATH:$PYENV_ROOT/bin"

enable_pyenv() {
    if command -v pyenv > /dev/null; then
        eval "$(pyenv init --path)"
    fi
}
enable_pyenv

install_pyenv() {
    curl https://pyenv.run | bash
    enable_pyenv
    for version in $PYTHON_VERSIONS; do
        pyenv install $version
    done
}

update_version() {
    sed -i "s/^\s*package_version.*/package_version = '$TKRZW_PYTHON_VERSION'/g" setup.py
    cat setup.py
}

build_library() {
    cd "$LIBRARY_DIR"
    ./configure --enable-static --disable-shared
    make -j2
    make check
    make install
}

install_build_wheel() {
    pip install -U pip
    pip install -U build auditwheel
}

build_wheel() {
    cd "$MODULE_DIR"
    update_version
    python -m build --wheel
}
