#!/bin/sh

BASE="$PWD"
LIBRARY_DIR="$BASE/tkrzw-$TKRZW_VERSION"
MODULE_DIR="$BASE/tkrzw-python-$TKRZW_PYTHON_VERSION"

export PYTHONUSERBASE="$HOME/python"
export PATH="$PATH:$HOME/python/bin"

update_version() {
    sed -i "s/^\s*package_version.*/package_version = '$TKRZW_PYTHON_VERSION'/g" setup.py
    cat setup.py
}

build_library() {
    cd "$LIBRARY_DIR"
    ./configure --enable-static --disable-shared
    make -j2
    make check
    make install
}

install_build_wheel() {
    pip install -U pip
    pip install -U build auditwheel
}

build_wheel() {
    cd "$MODULE_DIR"
    update_version
    python -m build --wheel
    auditwheel repair "./dist/tkrzw-$TKRZW_PYTHON_VERSION-cp310-cp310-linux_x86_64.whl"
    auditwheel show "./wheelhouse/tkrzw-$TKRZW_PYTHON_VERSION-cp310-cp310-musllinux_1_2_x86_64.whl"
}
