on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      TKRZW_VERSION: 1.0.24
      TKRZW_PYTHON_VERSION: 0.1.28
      LDFLAGS: "-flto"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create cache dir
        run: |
          mkdir -p ${{ github.workspace }}/library-${{ env.TKRZW_VERSION }}
        shell: bash

      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1
        with:
          volumes: ${{ github.workspace }}/library-${{ env.TKRZW_VERSION }}:/usr/local

      - name: Setup build as root
        run: |
          ./alpine setup
        shell: alpine.sh --root {0}

      - name: Cache Library Build
        id: library-build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/library-${{ env.TKRZW_VERSION }}
          key: library-${{ env.TKRZW_VERSION }}

      - name: Build library
        if: steps.library-build.outputs.cache-hit != 'true'
        run: |
          ./alpine library
        shell: alpine.sh {0}

      - name: Build wheel
        run: |
          ./alpine wheel
        shell: alpine.sh {0}

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: ${{ github.workspace }}/common
